### ISSUE TITLE
The code is incomplete

### ISSUE THREAD

**Issue by 1058781049** [benchen4395/CCDN_code#1]
May I ask if it is possible to share the tags of gopro and ueye datasets

**Comment by RenRunyesh** [comment]
May I ask if it is possible to share the tags of gopro and ueye datasets

**Comment by benchen4395** [comment]
The code is complete, but the dataset is not belong to us. So we should ask the answer.

**Comment by benchen4395** [comment]
> May I ask if it is possible to share the tags of gopro and ueye datasets

Here, we release all the training dataset and eval dataset for CCDN and RCDN. Furthermore, we also release all the annotated corner locations for training dataset.

- [Training dataset](https://huggingface.co/datasets/benchen4395/CCDN_eval_dataset): All (a total of 8050 images) were converted to gray-scale images and resized into VGA resolution with (640x480) pixels as the training dataset,
- [Eval dataset](https://huggingface.co/datasets/benchen4395/CCDN_training_dataset): Including three public datasets: GoPro (100 images), Mesa (206 images) and uEye (206 images), original from [ROCHADE](https://link.springer.com/chapter/10.1007/978-3-319-10593-2_50) (ECCV 2014 oral).
__If you use these datasets, please cite our two articles. Thanks.__

**Comment by benchen4395** [comment]
> May I ask if it is possible to share the tags of gopro and ueye datasets

Here, we release all the training dataset and eval dataset for CCDN and RCDN. Furthermore, we also release all the annotated corner locations for training dataset.

- [Training dataset](https://huggingface.co/datasets/benchen4395/CCDN_eval_dataset): All (a total of 8050 images) were converted to gray-scale images and resized into VGA resolution with (640x480) pixels as the training dataset,
- [Eval dataset](https://huggingface.co/datasets/benchen4395/CCDN_training_dataset): Including three public datasets: GoPro (100 images), Mesa (206 images) and uEye (206 images), original from [ROCHADE](https://link.springer.com/chapter/10.1007/978-3-319-10593-2_50) (ECCV 2014 oral).
__If you use these datasets, please cite our two articles. Thanks.__

**Comment by benchen4395** [comment]
> May I ask if it is possible to share the tags of gopro and ueye datasets

> May I ask if it is possible to share the tags of gopro and ueye datasets

Here, we release all the training dataset and eval dataset for CCDN and RCDN. Furthermore, we also release all the annotated corner locations for training dataset.

- [Training dataset](https://huggingface.co/datasets/benchen4395/CCDN_eval_dataset): All (a total of 8050 images) were converted to gray-scale images and resized into VGA resolution with (640x480) pixels as the training dataset,
- [Eval dataset](https://huggingface.co/datasets/benchen4395/CCDN_training_dataset): Including three public datasets: GoPro (100 images), Mesa (206 images) and uEye (206 images), original from [ROCHADE](https://link.springer.com/chapter/10.1007/978-3-319-10593-2_50) (ECCV 2014 oral).
__If you use these datasets, please cite our two articles. Thanks.__
