### ISSUE TITLE
请问能否分享一下数据集和标签？

### ISSUE THREAD

**Issue by LinYuOu** [benchen4395/CCDN_code#2]
您好，最近我们也在做相机标定的相关工作，请问能否分享一下数据集和标签？

**Comment by LinYuOu** [comment]
或者可以分享一下数据格式吗？

**Comment by benchen4395** [comment]
Here, we release all the training dataset and eval dataset for CCDN and RCDN. Furthermore, we also release all the annotated corner locations for training dataset.

- [Training dataset](https://huggingface.co/datasets/benchen4395/CCDN_eval_dataset): All (a total of 8050 images) were converted to gray-scale images and resized into VGA resolution with (640x480) pixels as the training dataset,
- [Eval dataset](https://huggingface.co/datasets/benchen4395/CCDN_training_dataset): Including three public datasets: GoPro (100 images), Mesa (206 images) and uEye (206 images), original from [ROCHADE](https://link.springer.com/chapter/10.1007/978-3-319-10593-2_50) (ECCV 2014 oral).
__If you use these datasets, please cite our two articles. Thanks.__
