### ISSUE TITLE
数据集分享

### ISSUE THREAD

**Issue by WangDongBUAA** [benchen4395/CCDN_code#3]
代码不全啊，作者能否可以分享一下数据集

**Comment by benchen4395** [comment]
Here, we release all the training dataset and eval dataset for CCDN and RCDN. Furthermore, we also release all the annotated corner locations for training dataset.

- [Training dataset](https://huggingface.co/datasets/benchen4395/CCDN_eval_dataset): All (a total of 8050 images) were converted to gray-scale images and resized into VGA resolution with (640x480) pixels as the training dataset,
- [Eval dataset](https://huggingface.co/datasets/benchen4395/CCDN_training_dataset): Including three public datasets: GoPro (100 images), Mesa (206 images) and uEye (206 images), original from [ROCHADE](https://link.springer.com/chapter/10.1007/978-3-319-10593-2_50) (ECCV 2014 oral).
__If you use these datasets, please cite our two articles. Thanks.__

**Comment by WangDongBUAA** [comment]
感谢作者的分享，太强了
我有个问题就是，训练数据和标签都是怎么预处理的，训练数据每一张图片都reiszed成了统一的尺寸，标签是对每一个真值点的坐标生成‘1’，其他位置生成‘0’，大概是这个思路吧。我看new_chessboards_train.py训练代码中有关于这一部分的处理，
train_data, train_label = traindatas()

traindatas这个类是怎么定义的呢

如果我的棋盘图片的背景比较复杂，有一些光照的影响，这样后续可以怎么处理呢？

谢谢作者！

**Comment by benchen4395** [comment]
对于图像的预处理，如论文中所说，resize成同一个尺寸，然后灰度化，做了图像的normalization，这个也是traindatas函数中定义的处理方式；

对于图片背景有光照、偏置、变形等处理，以及做完基础检测后的亚像素细化，可以参考我们这篇文章： [Automatic checkerboard detection for camera calibration](https://ieeexplore.ieee.org/document/9428389) (ICME 2021 oral)

祝好！

**Comment by WangDongBUAA** [comment]
好的，再次感谢！

**Comment by benchen4395** [comment]
> 好的，再次感谢！

你也可以参考一下这篇文章：https://arxiv.org/pdf/2307.03505
算是对之前两篇文章的补充；希望对你有帮助

**Comment by WangDongBUAA** [comment]
好的，谢谢！
我还想请教下，对于误检测的点，有什么好的办法可以去除，进一步提高检测的精度呢
最好的方法是后处理refine调优吗
